### ISSUE TITLE
error in install requirements action-turtorials-py==0.9.4

### ISSUE THREAD

**Issue by Scodive** [masskro0/carla_connected_mobility#1]
ERROR: Could not find a version that satisfies the requirement action-tutorials-py==0.9.4 (from versions: 0.0.1)
ERROR: No matching distribution found for action-tutorials-py==0.9.4

**Comment by masskro0** [comment]
Thanks for the notice! I used the wrong virtual environment, the issue is now fixed in commit 47646c5501e89238018e0ce722680bb65a8af544
